DELETE http://localhost:8080/events/2/register
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QzQHRlc3QuY29tIiwiZXhwIjoxNzQyNzg4NDg4LCJ1c2VySWQiOjN9.Cf2AhrJj3j_kgB5T6RmopABKn1LQYVzG12t54gJ0Zq8